/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author MJS-X
 */
public class OperasiDuaAngkaGUI extends javax.swing.JFrame {

    /**
     * Creates new form OperasiDuaAngkaGUI
     */
    public OperasiDuaAngkaGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        angka1TextField = new javax.swing.JTextField();
        angka2TextField = new javax.swing.JTextField();
        hasilTextField = new javax.swing.JTextField();
        angkapertamaLabel = new javax.swing.JLabel();
        angkakeduaLabel = new javax.swing.JLabel();
        penjumlahanButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        hasilLabel = new javax.swing.JLabel();
        penguranganButton = new javax.swing.JButton();
        perkalianButton = new javax.swing.JButton();
        pembagianButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        hasilTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilTextFieldActionPerformed(evt);
            }
        });

        angkapertamaLabel.setText("Angka Pertama");

        angkakeduaLabel.setText("Angka Kedua");

        penjumlahanButton.setText("Penjumlahan");
        penjumlahanButton.setToolTipText("");
        penjumlahanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjumlahanButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        hasilLabel.setText("Hasil");

        penguranganButton.setText("Pengurangan");
        penguranganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penguranganButtonActionPerformed(evt);
            }
        });

        perkalianButton.setText("Perkalian");
        perkalianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perkalianButtonActionPerformed(evt);
            }
        });

        pembagianButton.setText("Pembagian");
        pembagianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembagianButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(angkapertamaLabel)
                    .addComponent(angkakeduaLabel)
                    .addComponent(hasilLabel))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angka1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penjumlahanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(penguranganButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(perkalianButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pembagianButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(angka1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(angkapertamaLabel)
                    .addComponent(penjumlahanButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(angka2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(angkakeduaLabel)
                        .addComponent(penguranganButton)))
                .addGap(18, 18, 18)
                .addComponent(perkalianButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hasilTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilLabel)
                    .addComponent(pembagianButton))
                .addGap(18, 18, 18)
                .addComponent(hapusButton)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void penjumlahanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjumlahanButtonActionPerformed
        double a = Double.parseDouble(angka1TextField.getText());
        double b = Double.parseDouble(angka2TextField.getText());
                double  hasil = a + b;
                hasilTextField.setText (hasil + "");
    }//GEN-LAST:event_penjumlahanButtonActionPerformed

    private void penguranganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penguranganButtonActionPerformed
        double a = Double.parseDouble(angka1TextField.getText());
        double b = Double.parseDouble(angka2TextField.getText());
                double  hasil = a - b;
                hasilTextField.setText (hasil + "");
    }//GEN-LAST:event_penguranganButtonActionPerformed

    private void perkalianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perkalianButtonActionPerformed
        double a = Double.parseDouble(angka1TextField.getText());
        double b = Double.parseDouble(angka2TextField.getText());
                double  hasil = a * b;
                hasilTextField.setText (hasil + "");
    }//GEN-LAST:event_perkalianButtonActionPerformed

    private void pembagianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembagianButtonActionPerformed
        double a = Double.parseDouble(angka1TextField.getText());
        double b = Double.parseDouble(angka2TextField.getText());
                double  hasil = a / b;
                hasilTextField.setText (hasil + "");
    }//GEN-LAST:event_pembagianButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        angka1TextField.setText ("");
        angka2TextField.setText ("");
        hasilTextField.setText ("");
        angka1TextField.requestFocus();
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void hasilTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperasiDuaAngkaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperasiDuaAngkaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angka1TextField;
    private javax.swing.JTextField angka2TextField;
    private javax.swing.JLabel angkakeduaLabel;
    private javax.swing.JLabel angkapertamaLabel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField hasilTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pembagianButton;
    private javax.swing.JButton penguranganButton;
    private javax.swing.JButton penjumlahanButton;
    private javax.swing.JButton perkalianButton;
    // End of variables declaration//GEN-END:variables
}
